### ISSUE TITLE
Weird time

### ISSUE THREAD

**Issue by aquilax** [ttygde/pokoy#6]
After I suspended my laptop yesterday and resumed today, I got some weird times from `pokoy`:

``` bash
$ pokoy 
34:59
-56176:71581852:50
```

**Comment by ttygde** [comment]
This is strange. Unfortunately, now I don't have laptop for testing.

**Comment by aquilax** [comment]
My wild guess is that the time for the brake passed, while the computer was suspended, and that overflowed the timer.

**Comment by lich-tex** [comment]
The issue is fixed after @matmatyk commit.
