### ISSUE TITLE
Undocumented dependencies and unknown CFLAGS

### ISSUE THREAD

**Issue by mlromramse** [ttygde/pokoy#8]
## I like your application.

However when installing it on my LinuxMint 13 distribution I had to install the following to be able to run make:
- libx11-xcb-dev
- libxcb-keysyms1-dev
- libcxb-iccm4-dev
- libxcb-screensaver0-dev

Furthermore I had to change the `CFLAGS` row to:

```
CFLAGS = -std=gnu1x -02
```

After this it compiled, installed and runs beautifully, 

Please change the Makefile and add this to your doc, in your own words, so that more people than C programmers can install this easily. Maybe a configure file could do it?

As you probably understand I am not a C programmer. I got help.

Thanks!

**Comment by matmatyk** [comment]
Other solution: Move to CMake which will handle all dependencies.

**Comment by matmatyk** [comment]
Added information about dependencies to README file. Additionally switched to CMake which will inform the user which libraries can't be found in OS.
