### ISSUE TITLE
Time between breaks has to be <60 minutes?

### ISSUE THREAD

**Issue by m1nde** [ttygde/pokoy#9]
Hey, I want to take a break every 2 hours,so 120 mins. 
I added the line `break 120:00 10:00 10:00`
But when I start pokoy with this config and inquire the time till the next break, it gives me the strange output of 7140:119:58... What is that supped to mean?

**Comment by lich-tex** [comment]
Fixed in 21c550858ecc1caabfc50c01fdff290f8c0c6a29
